sms_app/topics/config/routes.rb
Topics::Application.routes.draw do
  
  devise_for :users

  match 'good_reply/:id' => 'comments#good_reply',:as => :good_reply
  match 'home/latest' => 'home#latest',:as => :latest_home_index

  resources :questions do
    resources :comments
  end
  resources :ideas do
    resources :comments
  end
  resources :problems do
    resources :comments
  end
  resources :praises do
    resources :comments
  end

  

  root :to => 'home#index'

end

sms_app/topics/app/models/question.rb
class Question < ActiveRecord::Base
  	attr_accessible :content, :title, :user_id
  	has_many :comments, :as => :commentable, :dependent => :destroy
  	belongs_to :user
end

sms_app/topics/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
  	@questions = Question.all
	end
  
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params[:question])
    respond_to do |format|
      format.html{
        if @question.save
          flash[:notice]="Question created scuccessfully"
          redirect_to questions_url
        else
          flash[:error]="Question not created"
           render "new"
        end
      }
      format.js{
        if @question.save
          #Any message 
        else
          #Error message 
        end
        @questions = Question.all
      }
    end    
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

	def update
  	@question = Question.find(params[:id])
    
    if @question.update_attributes(params[:question])
      flash[:notice]="Question updated scuccessfully"
		  redirect_to action:"index"
    else
      flash[:error]="Question not updated"
		  render "edit"
    end
  end

	def destroy
    @question = Question.find(params[:id])
    
    if @question.destroy
		  flash[:notice]="Question deleted scuccessfully"
	  else
		  flash[:error]="Question not deleted"
	  end
	  redirect_to questions_url
  end

end

sms_app/topics/app/helpers/questions_helper.rb
module QuestionsHelper
end

sms_app/topics/app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sms_app/topics/app/views/questions/create.js.erb
$('#topics_listing_box').html("<%= escape_javascript(render :partial => 'shared/questions_list',:locals => { :questions => @questions } ) %>");

sms_app/topics/app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

sms_app/topics/app/views/questions/index.html.erb
<div id="questions_index">
	<%= render partial: 'shared/questions_list' ,locals: {questions: @questions} %>
</div>

sms_app/topics/app/views/questions/index.js.erb
$('#topics_listing_box').html("<%= escape_javascript(render :partial => 'shared/questions_list',:locals => { :questions => @questions } ) %>");

sms_app/topics/app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

sms_app/topics/app/views/questions/show.html.erb
<div >
    <p class="posted_by">
        <%= index+=1 %>.
        <%= comment.content.html_safe %>
        <% if comment.count.present? %>
            <%= link_to "Good Reply(<span>#{comment.count}</span>)".html_safe , good_reply_path(comment) ,:id => "good_reply"%>
        <% else %>
            <%= link_to "good reply", good_reply_path(comment) %>
        <% end %>
        <%= link_to "Comment", "#" %>
    </p>
</div>